"""Initial Migration

Revision ID: 535f892527d2
Revises: 08ef447e6268
Create Date: 2021-06-21 22:39:30.873520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535f892527d2'
down_revision = '08ef447e6268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'update')
    op.drop_column('blogs', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('delete', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('update', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
